# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       swordfish

# >> macros
# << macros

Summary:    File manager
Version:    0.0.0.20140329.0f1d929
Release:    1
Group:      Applications/System
License:    GPLv2+
URL:        https://github.com/mauios/swordfish.git
Source0:    swordfish-%{version}.tar.xz
Source100:  swordfish.yaml
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  cmake
BuildRequires:  qt5-qttools-linguist

%description
File manager for the Hawaii desktop environment.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/swordfish
%{_libdir}/hawaii/qml/Swordfish/*
%{_datadir}/hawaii-2048/styles/*
%{_datadir}/dbus-1/services/*
%{_datadir}/applications/*
%{_datadir}/swordfish/translations/*
# >> files
# << files
